version: '2'

services:
  bot:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres:10
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
